
# relative path from 'home'
snakefile: 'WESPipeline2/snakefile_call_03.py'
conda: 'WESPipeline2/envs/'
scripts: 'scripts/'
process_path: 'ANALYSES_WES/'

# absolute path
store_path: '/mnt/stor-rw/users/eugenio_wes/'

outfolder: '181214_call_all_trio'

# FOR snakefile_call:
# it must be a table with following columns:
# 'tumor', 'normal', 'tumor_directory', 'normal_directory'
input_list: 'RUN/181214_call_all_trio/input_list.tsv'


dataset: 'data_ref_02/20181106_dataset.tsv'

rsID_dict: 'ucsc/181031_filter_snp138Common/181031_snp138Common_ucsc_99CI.json'

cores: '27'
disk: '1'
cpu_type: 'NA'
n_sim: '1'
n_cpu: '1'
threads: 27

keepgoing: True

fasta:
  MT: 'data_ref_02/MT.fasta'
  genome: 'data_ref_02/human_g1k_v37.fasta'
  nextera: 'data_ref_02/nextera.fasta'
  nextera_expanded: 'data_ref_02/nextera_expanded.fasta'
  truseq: 'data_ref_02/truseq.fasta'
  truseq_rapid: 'data_ref_02/truseq_rapid.fasta'
  nextera_dna_exome: 'data_ref_02/nextera_dna_exome.fasta'

bed:
  MT: 'data_ref_02/MT'
  nextera: 'data_ref_02/nexterarapidcapture_exome_targetedregions_v1.2'
  nextera_expanded: 'data_ref_02/nexterarapidcapture_expandedexome_targetedregions'
  truseq: 'data_ref_02/truseq-exome-targeted-regions-manifest-v1-2'
  truseq_rapid: 'data_ref_02/truseq-rapid-exome-targeted-regions-manifest-v1-2'
  nextera_dna_exome: 'data_ref_02/nextera-dna-exome-targeted-regions-manifest-v1-2'

varscan_arguments:
  min_avg_qual: '15'
  strand_filter: '1'
  min_var_freq: '0.05'
  somatic_p_value: '0.05'

somaticFilter:
  min_coverage: '1'
  min_reads2: '2'
  min_var_freq: '0.1'

protocols:
  genome: 'refGene,cytoBand,genomicSuperDups,esp6500siv2_all,snp138,1000g2014oct_all,exac03nontcga,ljb26_all,clinvar_20180603,cosmic70'
  mt: 'ensGene'

operations:
  genome: 'g,r,r,f,f,f,f,f,f,f'
  mt: 'g'


ref-files:
    ## For IndelRealigner
#    indels_ref: 'data_ref_02/Mills_and_1000G_gold_standard.indels.b37.vcf' # The current best set of known indels to be used for local realignment
    dbsnp: 'data_ref_02/dbsnp_138.b37.vcf' # SNPs database
    cosmic: 'data_ref_02/b37_cosmic_v54_120711.vcf' # Catalog of somatic mutation in cancer
    humandb: 'softwares/annovar/humandb' # Annovar human databases folder
    buildver: 'hg19' # Set build version
    buildver_mt: 'GRCh37_MT' # Set parameter command for annotating mitochondria variants

folders:
    softwares: 'softwares/'
    annovar: 'softwares/annovar/'

softwares:
    gatk: 'softwares/GenomeAnalysisTK-3.4-0/GenomeAnalysisTK.jar'
    muTect: 'softwares/muTect-1.1.4/muTect-1.1.4.jar'
    annotate: 'softwares/annovar/annotate_variation.pl'
    tableannovar: 'softwares/annovar/table_annovar.pl'
    varscan: 'softwares/VarScan.v2.3.9.jar'

sample-details:
    platform: 'illumina' # Set platform for mapping

annovar_dbs:
    hg19_refGene: 'softwares/annovar/humandb/hg19_refGene.txt'
    hg19_cytoBand: 'softwares/annovar/humandb/hg19_cytoBand.txt'
    hg19_gSd: 'softwares/annovar/humandb/hg19_genomicSuperDups.txt'
    hg19_esp: 'softwares/annovar/humandb/hg19_esp6500siv2_all.txt'
    hg19_snp138: 'softwares/annovar/humandb/hg19_snp138.txt'
    hg19_1000g2014oct: 'softwares/annovar/humandb/hg19_ALL.sites.2014_10.txt'
    hg19_exac03nontcga: 'softwares/annovar/humandb/hg19_exac03nontcga.txt'
    hg19_ljb26_all: 'softwares/annovar/humandb/hg19_ljb26_all.txt'
    hg19_clinvar_20180603: 'softwares/annovar/humandb/hg19_clinvar_20180603.txt'
    hg19_cosmic70: 'softwares/annovar/humandb/hg19_cosmic70.txt'
